// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: src/grpc/proto/bahan_makanan/bahan_makanan.proto

package bahan_makanan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BahanMakanan struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kode              string                 `protobuf:"bytes,2,opt,name=kode,proto3" json:"kode,omitempty"`
	NamaBahanMakanan  string                 `protobuf:"bytes,3,opt,name=nama_bahan_makanan,json=namaBahanMakanan,proto3" json:"nama_bahan_makanan,omitempty"`
	AirG              float64                `protobuf:"fixed64,4,opt,name=air_g,json=airG,proto3" json:"air_g,omitempty"`
	EnergiKal         float64                `protobuf:"fixed64,5,opt,name=energi_kal,json=energiKal,proto3" json:"energi_kal,omitempty"`
	ProteinG          float64                `protobuf:"fixed64,6,opt,name=protein_g,json=proteinG,proto3" json:"protein_g,omitempty"`
	LemakG            float64                `protobuf:"fixed64,7,opt,name=lemak_g,json=lemakG,proto3" json:"lemak_g,omitempty"`
	KarbohidratG      float64                `protobuf:"fixed64,8,opt,name=karbohidrat_g,json=karbohidratG,proto3" json:"karbohidrat_g,omitempty"`
	SeratG            *float64               `protobuf:"fixed64,9,opt,name=serat_g,json=seratG,proto3,oneof" json:"serat_g,omitempty"`
	AbuG              float64                `protobuf:"fixed64,10,opt,name=abu_g,json=abuG,proto3" json:"abu_g,omitempty"`
	KalsiumCaMg       *float64               `protobuf:"fixed64,11,opt,name=kalsium_ca_mg,json=kalsiumCaMg,proto3,oneof" json:"kalsium_ca_mg,omitempty"`
	FosforPMg         *float64               `protobuf:"fixed64,12,opt,name=fosfor_p_mg,json=fosforPMg,proto3,oneof" json:"fosfor_p_mg,omitempty"`
	BesiFeMg          *float64               `protobuf:"fixed64,13,opt,name=besi_fe_mg,json=besiFeMg,proto3,oneof" json:"besi_fe_mg,omitempty"`
	NatriumNaMg       *float64               `protobuf:"fixed64,14,opt,name=natrium_na_mg,json=natriumNaMg,proto3,oneof" json:"natrium_na_mg,omitempty"`
	KaliumKaMg        *float64               `protobuf:"fixed64,15,opt,name=kalium_ka_mg,json=kaliumKaMg,proto3,oneof" json:"kalium_ka_mg,omitempty"`
	TembagaCuMg       *float64               `protobuf:"fixed64,16,opt,name=tembaga_cu_mg,json=tembagaCuMg,proto3,oneof" json:"tembaga_cu_mg,omitempty"`
	SengZnMg          *float64               `protobuf:"fixed64,17,opt,name=seng_zn_mg,json=sengZnMg,proto3,oneof" json:"seng_zn_mg,omitempty"`
	RetinolVitAMcg    *float64               `protobuf:"fixed64,18,opt,name=retinol_vit_a_mcg,json=retinolVitAMcg,proto3,oneof" json:"retinol_vit_a_mcg,omitempty"`
	BetaKarotenMcg    *float64               `protobuf:"fixed64,19,opt,name=beta_karoten_mcg,json=betaKarotenMcg,proto3,oneof" json:"beta_karoten_mcg,omitempty"`
	KarotenTotalMcg   *float64               `protobuf:"fixed64,20,opt,name=karoten_total_mcg,json=karotenTotalMcg,proto3,oneof" json:"karoten_total_mcg,omitempty"`
	ThiaminVitB1Mg    *float64               `protobuf:"fixed64,21,opt,name=thiamin_vit_b1_mg,json=thiaminVitB1Mg,proto3,oneof" json:"thiamin_vit_b1_mg,omitempty"`
	RiboflavinVitB2Mg *float64               `protobuf:"fixed64,22,opt,name=riboflavin_vit_b2_mg,json=riboflavinVitB2Mg,proto3,oneof" json:"riboflavin_vit_b2_mg,omitempty"`
	NiasinMg          *float64               `protobuf:"fixed64,23,opt,name=niasin_mg,json=niasinMg,proto3,oneof" json:"niasin_mg,omitempty"`
	VitaminCMg        *float64               `protobuf:"fixed64,24,opt,name=vitamin_c_mg,json=vitaminCMg,proto3,oneof" json:"vitamin_c_mg,omitempty"`
	BddPersen         float64                `protobuf:"fixed64,25,opt,name=bdd_persen,json=bddPersen,proto3" json:"bdd_persen,omitempty"`
	MentahOlahan      string                 `protobuf:"bytes,26,opt,name=mentah_olahan,json=mentahOlahan,proto3" json:"mentah_olahan,omitempty"`
	KelompokMakanan   string                 `protobuf:"bytes,27,opt,name=kelompok_makanan,json=kelompokMakanan,proto3" json:"kelompok_makanan,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BahanMakanan) Reset() {
	*x = BahanMakanan{}
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BahanMakanan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BahanMakanan) ProtoMessage() {}

func (x *BahanMakanan) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BahanMakanan.ProtoReflect.Descriptor instead.
func (*BahanMakanan) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescGZIP(), []int{0}
}

func (x *BahanMakanan) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BahanMakanan) GetKode() string {
	if x != nil {
		return x.Kode
	}
	return ""
}

func (x *BahanMakanan) GetNamaBahanMakanan() string {
	if x != nil {
		return x.NamaBahanMakanan
	}
	return ""
}

func (x *BahanMakanan) GetAirG() float64 {
	if x != nil {
		return x.AirG
	}
	return 0
}

func (x *BahanMakanan) GetEnergiKal() float64 {
	if x != nil {
		return x.EnergiKal
	}
	return 0
}

func (x *BahanMakanan) GetProteinG() float64 {
	if x != nil {
		return x.ProteinG
	}
	return 0
}

func (x *BahanMakanan) GetLemakG() float64 {
	if x != nil {
		return x.LemakG
	}
	return 0
}

func (x *BahanMakanan) GetKarbohidratG() float64 {
	if x != nil {
		return x.KarbohidratG
	}
	return 0
}

func (x *BahanMakanan) GetSeratG() float64 {
	if x != nil && x.SeratG != nil {
		return *x.SeratG
	}
	return 0
}

func (x *BahanMakanan) GetAbuG() float64 {
	if x != nil {
		return x.AbuG
	}
	return 0
}

func (x *BahanMakanan) GetKalsiumCaMg() float64 {
	if x != nil && x.KalsiumCaMg != nil {
		return *x.KalsiumCaMg
	}
	return 0
}

func (x *BahanMakanan) GetFosforPMg() float64 {
	if x != nil && x.FosforPMg != nil {
		return *x.FosforPMg
	}
	return 0
}

func (x *BahanMakanan) GetBesiFeMg() float64 {
	if x != nil && x.BesiFeMg != nil {
		return *x.BesiFeMg
	}
	return 0
}

func (x *BahanMakanan) GetNatriumNaMg() float64 {
	if x != nil && x.NatriumNaMg != nil {
		return *x.NatriumNaMg
	}
	return 0
}

func (x *BahanMakanan) GetKaliumKaMg() float64 {
	if x != nil && x.KaliumKaMg != nil {
		return *x.KaliumKaMg
	}
	return 0
}

func (x *BahanMakanan) GetTembagaCuMg() float64 {
	if x != nil && x.TembagaCuMg != nil {
		return *x.TembagaCuMg
	}
	return 0
}

func (x *BahanMakanan) GetSengZnMg() float64 {
	if x != nil && x.SengZnMg != nil {
		return *x.SengZnMg
	}
	return 0
}

func (x *BahanMakanan) GetRetinolVitAMcg() float64 {
	if x != nil && x.RetinolVitAMcg != nil {
		return *x.RetinolVitAMcg
	}
	return 0
}

func (x *BahanMakanan) GetBetaKarotenMcg() float64 {
	if x != nil && x.BetaKarotenMcg != nil {
		return *x.BetaKarotenMcg
	}
	return 0
}

func (x *BahanMakanan) GetKarotenTotalMcg() float64 {
	if x != nil && x.KarotenTotalMcg != nil {
		return *x.KarotenTotalMcg
	}
	return 0
}

func (x *BahanMakanan) GetThiaminVitB1Mg() float64 {
	if x != nil && x.ThiaminVitB1Mg != nil {
		return *x.ThiaminVitB1Mg
	}
	return 0
}

func (x *BahanMakanan) GetRiboflavinVitB2Mg() float64 {
	if x != nil && x.RiboflavinVitB2Mg != nil {
		return *x.RiboflavinVitB2Mg
	}
	return 0
}

func (x *BahanMakanan) GetNiasinMg() float64 {
	if x != nil && x.NiasinMg != nil {
		return *x.NiasinMg
	}
	return 0
}

func (x *BahanMakanan) GetVitaminCMg() float64 {
	if x != nil && x.VitaminCMg != nil {
		return *x.VitaminCMg
	}
	return 0
}

func (x *BahanMakanan) GetBddPersen() float64 {
	if x != nil {
		return x.BddPersen
	}
	return 0
}

func (x *BahanMakanan) GetMentahOlahan() string {
	if x != nil {
		return x.MentahOlahan
	}
	return ""
}

func (x *BahanMakanan) GetKelompokMakanan() string {
	if x != nil {
		return x.KelompokMakanan
	}
	return ""
}

type GetBahanMakananRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kode          string                 `protobuf:"bytes,1,opt,name=kode,proto3" json:"kode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBahanMakananRequest) Reset() {
	*x = GetBahanMakananRequest{}
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBahanMakananRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBahanMakananRequest) ProtoMessage() {}

func (x *GetBahanMakananRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBahanMakananRequest.ProtoReflect.Descriptor instead.
func (*GetBahanMakananRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescGZIP(), []int{1}
}

func (x *GetBahanMakananRequest) GetKode() string {
	if x != nil {
		return x.Kode
	}
	return ""
}

type GetBahanMakananByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBahanMakananByIdRequest) Reset() {
	*x = GetBahanMakananByIdRequest{}
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBahanMakananByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBahanMakananByIdRequest) ProtoMessage() {}

func (x *GetBahanMakananByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBahanMakananByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBahanMakananByIdRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescGZIP(), []int{2}
}

func (x *GetBahanMakananByIdRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBahanMakananByMentahOlahanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MentahOlahan  string                 `protobuf:"bytes,1,opt,name=mentah_olahan,json=mentahOlahan,proto3" json:"mentah_olahan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBahanMakananByMentahOlahanRequest) Reset() {
	*x = GetBahanMakananByMentahOlahanRequest{}
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBahanMakananByMentahOlahanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBahanMakananByMentahOlahanRequest) ProtoMessage() {}

func (x *GetBahanMakananByMentahOlahanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBahanMakananByMentahOlahanRequest.ProtoReflect.Descriptor instead.
func (*GetBahanMakananByMentahOlahanRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescGZIP(), []int{3}
}

func (x *GetBahanMakananByMentahOlahanRequest) GetMentahOlahan() string {
	if x != nil {
		return x.MentahOlahan
	}
	return ""
}

type GetBahanMakananByKelompokRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KelompokMakanan string                 `protobuf:"bytes,1,opt,name=kelompok_makanan,json=kelompokMakanan,proto3" json:"kelompok_makanan,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBahanMakananByKelompokRequest) Reset() {
	*x = GetBahanMakananByKelompokRequest{}
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBahanMakananByKelompokRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBahanMakananByKelompokRequest) ProtoMessage() {}

func (x *GetBahanMakananByKelompokRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBahanMakananByKelompokRequest.ProtoReflect.Descriptor instead.
func (*GetBahanMakananByKelompokRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescGZIP(), []int{4}
}

func (x *GetBahanMakananByKelompokRequest) GetKelompokMakanan() string {
	if x != nil {
		return x.KelompokMakanan
	}
	return ""
}

type UpdateBahanMakananRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BahanMakanan  *BahanMakanan          `protobuf:"bytes,2,opt,name=bahan_makanan,json=bahanMakanan,proto3" json:"bahan_makanan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBahanMakananRequest) Reset() {
	*x = UpdateBahanMakananRequest{}
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBahanMakananRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBahanMakananRequest) ProtoMessage() {}

func (x *UpdateBahanMakananRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBahanMakananRequest.ProtoReflect.Descriptor instead.
func (*UpdateBahanMakananRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBahanMakananRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBahanMakananRequest) GetBahanMakanan() *BahanMakanan {
	if x != nil {
		return x.BahanMakanan
	}
	return nil
}

type BahanMakananResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BahanMakanan  *BahanMakanan          `protobuf:"bytes,1,opt,name=bahan_makanan,json=bahanMakanan,proto3" json:"bahan_makanan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BahanMakananResponse) Reset() {
	*x = BahanMakananResponse{}
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BahanMakananResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BahanMakananResponse) ProtoMessage() {}

func (x *BahanMakananResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BahanMakananResponse.ProtoReflect.Descriptor instead.
func (*BahanMakananResponse) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescGZIP(), []int{6}
}

func (x *BahanMakananResponse) GetBahanMakanan() *BahanMakanan {
	if x != nil {
		return x.BahanMakanan
	}
	return nil
}

type ListBahanMakananResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BahanMakanan  []*BahanMakanan        `protobuf:"bytes,1,rep,name=bahan_makanan,json=bahanMakanan,proto3" json:"bahan_makanan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBahanMakananResponse) Reset() {
	*x = ListBahanMakananResponse{}
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBahanMakananResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBahanMakananResponse) ProtoMessage() {}

func (x *ListBahanMakananResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBahanMakananResponse.ProtoReflect.Descriptor instead.
func (*ListBahanMakananResponse) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescGZIP(), []int{7}
}

func (x *ListBahanMakananResponse) GetBahanMakanan() []*BahanMakanan {
	if x != nil {
		return x.BahanMakanan
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescGZIP(), []int{8}
}

var File_src_grpc_proto_bahan_makanan_bahan_makanan_proto protoreflect.FileDescriptor

const file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDesc = "" +
	"\n" +
	"0src/grpc/proto/bahan_makanan/bahan_makanan.proto\x12\rbahan_makanan\"\xed\t\n" +
	"\fBahanMakanan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04kode\x18\x02 \x01(\tR\x04kode\x12,\n" +
	"\x12nama_bahan_makanan\x18\x03 \x01(\tR\x10namaBahanMakanan\x12\x13\n" +
	"\x05air_g\x18\x04 \x01(\x01R\x04airG\x12\x1d\n" +
	"\n" +
	"energi_kal\x18\x05 \x01(\x01R\tenergiKal\x12\x1b\n" +
	"\tprotein_g\x18\x06 \x01(\x01R\bproteinG\x12\x17\n" +
	"\alemak_g\x18\a \x01(\x01R\x06lemakG\x12#\n" +
	"\rkarbohidrat_g\x18\b \x01(\x01R\fkarbohidratG\x12\x1c\n" +
	"\aserat_g\x18\t \x01(\x01H\x00R\x06seratG\x88\x01\x01\x12\x13\n" +
	"\x05abu_g\x18\n" +
	" \x01(\x01R\x04abuG\x12'\n" +
	"\rkalsium_ca_mg\x18\v \x01(\x01H\x01R\vkalsiumCaMg\x88\x01\x01\x12#\n" +
	"\vfosfor_p_mg\x18\f \x01(\x01H\x02R\tfosforPMg\x88\x01\x01\x12!\n" +
	"\n" +
	"besi_fe_mg\x18\r \x01(\x01H\x03R\bbesiFeMg\x88\x01\x01\x12'\n" +
	"\rnatrium_na_mg\x18\x0e \x01(\x01H\x04R\vnatriumNaMg\x88\x01\x01\x12%\n" +
	"\fkalium_ka_mg\x18\x0f \x01(\x01H\x05R\n" +
	"kaliumKaMg\x88\x01\x01\x12'\n" +
	"\rtembaga_cu_mg\x18\x10 \x01(\x01H\x06R\vtembagaCuMg\x88\x01\x01\x12!\n" +
	"\n" +
	"seng_zn_mg\x18\x11 \x01(\x01H\aR\bsengZnMg\x88\x01\x01\x12.\n" +
	"\x11retinol_vit_a_mcg\x18\x12 \x01(\x01H\bR\x0eretinolVitAMcg\x88\x01\x01\x12-\n" +
	"\x10beta_karoten_mcg\x18\x13 \x01(\x01H\tR\x0ebetaKarotenMcg\x88\x01\x01\x12/\n" +
	"\x11karoten_total_mcg\x18\x14 \x01(\x01H\n" +
	"R\x0fkarotenTotalMcg\x88\x01\x01\x12.\n" +
	"\x11thiamin_vit_b1_mg\x18\x15 \x01(\x01H\vR\x0ethiaminVitB1Mg\x88\x01\x01\x124\n" +
	"\x14riboflavin_vit_b2_mg\x18\x16 \x01(\x01H\fR\x11riboflavinVitB2Mg\x88\x01\x01\x12 \n" +
	"\tniasin_mg\x18\x17 \x01(\x01H\rR\bniasinMg\x88\x01\x01\x12%\n" +
	"\fvitamin_c_mg\x18\x18 \x01(\x01H\x0eR\n" +
	"vitaminCMg\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"bdd_persen\x18\x19 \x01(\x01R\tbddPersen\x12#\n" +
	"\rmentah_olahan\x18\x1a \x01(\tR\fmentahOlahan\x12)\n" +
	"\x10kelompok_makanan\x18\x1b \x01(\tR\x0fkelompokMakananB\n" +
	"\n" +
	"\b_serat_gB\x10\n" +
	"\x0e_kalsium_ca_mgB\x0e\n" +
	"\f_fosfor_p_mgB\r\n" +
	"\v_besi_fe_mgB\x10\n" +
	"\x0e_natrium_na_mgB\x0f\n" +
	"\r_kalium_ka_mgB\x10\n" +
	"\x0e_tembaga_cu_mgB\r\n" +
	"\v_seng_zn_mgB\x14\n" +
	"\x12_retinol_vit_a_mcgB\x13\n" +
	"\x11_beta_karoten_mcgB\x14\n" +
	"\x12_karoten_total_mcgB\x14\n" +
	"\x12_thiamin_vit_b1_mgB\x17\n" +
	"\x15_riboflavin_vit_b2_mgB\f\n" +
	"\n" +
	"_niasin_mgB\x0f\n" +
	"\r_vitamin_c_mg\",\n" +
	"\x16GetBahanMakananRequest\x12\x12\n" +
	"\x04kode\x18\x01 \x01(\tR\x04kode\",\n" +
	"\x1aGetBahanMakananByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"K\n" +
	"$GetBahanMakananByMentahOlahanRequest\x12#\n" +
	"\rmentah_olahan\x18\x01 \x01(\tR\fmentahOlahan\"M\n" +
	" GetBahanMakananByKelompokRequest\x12)\n" +
	"\x10kelompok_makanan\x18\x01 \x01(\tR\x0fkelompokMakanan\"m\n" +
	"\x19UpdateBahanMakananRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12@\n" +
	"\rbahan_makanan\x18\x02 \x01(\v2\x1b.bahan_makanan.BahanMakananR\fbahanMakanan\"X\n" +
	"\x14BahanMakananResponse\x12@\n" +
	"\rbahan_makanan\x18\x01 \x01(\v2\x1b.bahan_makanan.BahanMakananR\fbahanMakanan\"\\\n" +
	"\x18ListBahanMakananResponse\x12@\n" +
	"\rbahan_makanan\x18\x01 \x03(\v2\x1b.bahan_makanan.BahanMakananR\fbahanMakanan\"\a\n" +
	"\x05Empty2\x91\x05\n" +
	"\x13BahanMakananService\x12S\n" +
	"\x12GetAllBahanMakanan\x12\x14.bahan_makanan.Empty\x1a'.bahan_makanan.ListBahanMakananResponse\x12c\n" +
	"\x15GetBahanMakananByKode\x12%.bahan_makanan.GetBahanMakananRequest\x1a#.bahan_makanan.BahanMakananResponse\x12e\n" +
	"\x13GetBahanMakananById\x12).bahan_makanan.GetBahanMakananByIdRequest\x1a#.bahan_makanan.BahanMakananResponse\x12}\n" +
	"\x1dGetBahanMakananByMentahOlahan\x123.bahan_makanan.GetBahanMakananByMentahOlahanRequest\x1a'.bahan_makanan.ListBahanMakananResponse\x12u\n" +
	"\x19GetBahanMakananByKelompok\x12/.bahan_makanan.GetBahanMakananByKelompokRequest\x1a'.bahan_makanan.ListBahanMakananResponse\x12c\n" +
	"\x12UpdateBahanMakanan\x12(.bahan_makanan.UpdateBahanMakananRequest\x1a#.bahan_makanan.BahanMakananResponseB\x11Z\x0f.;bahan_makananb\x06proto3"

var (
	file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescOnce sync.Once
	file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescData []byte
)

func file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescGZIP() []byte {
	file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescOnce.Do(func() {
		file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDesc), len(file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDesc)))
	})
	return file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDescData
}

var file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_goTypes = []any{
	(*BahanMakanan)(nil),                         // 0: bahan_makanan.BahanMakanan
	(*GetBahanMakananRequest)(nil),               // 1: bahan_makanan.GetBahanMakananRequest
	(*GetBahanMakananByIdRequest)(nil),           // 2: bahan_makanan.GetBahanMakananByIdRequest
	(*GetBahanMakananByMentahOlahanRequest)(nil), // 3: bahan_makanan.GetBahanMakananByMentahOlahanRequest
	(*GetBahanMakananByKelompokRequest)(nil),     // 4: bahan_makanan.GetBahanMakananByKelompokRequest
	(*UpdateBahanMakananRequest)(nil),            // 5: bahan_makanan.UpdateBahanMakananRequest
	(*BahanMakananResponse)(nil),                 // 6: bahan_makanan.BahanMakananResponse
	(*ListBahanMakananResponse)(nil),             // 7: bahan_makanan.ListBahanMakananResponse
	(*Empty)(nil),                                // 8: bahan_makanan.Empty
}
var file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_depIdxs = []int32{
	0, // 0: bahan_makanan.UpdateBahanMakananRequest.bahan_makanan:type_name -> bahan_makanan.BahanMakanan
	0, // 1: bahan_makanan.BahanMakananResponse.bahan_makanan:type_name -> bahan_makanan.BahanMakanan
	0, // 2: bahan_makanan.ListBahanMakananResponse.bahan_makanan:type_name -> bahan_makanan.BahanMakanan
	8, // 3: bahan_makanan.BahanMakananService.GetAllBahanMakanan:input_type -> bahan_makanan.Empty
	1, // 4: bahan_makanan.BahanMakananService.GetBahanMakananByKode:input_type -> bahan_makanan.GetBahanMakananRequest
	2, // 5: bahan_makanan.BahanMakananService.GetBahanMakananById:input_type -> bahan_makanan.GetBahanMakananByIdRequest
	3, // 6: bahan_makanan.BahanMakananService.GetBahanMakananByMentahOlahan:input_type -> bahan_makanan.GetBahanMakananByMentahOlahanRequest
	4, // 7: bahan_makanan.BahanMakananService.GetBahanMakananByKelompok:input_type -> bahan_makanan.GetBahanMakananByKelompokRequest
	5, // 8: bahan_makanan.BahanMakananService.UpdateBahanMakanan:input_type -> bahan_makanan.UpdateBahanMakananRequest
	7, // 9: bahan_makanan.BahanMakananService.GetAllBahanMakanan:output_type -> bahan_makanan.ListBahanMakananResponse
	6, // 10: bahan_makanan.BahanMakananService.GetBahanMakananByKode:output_type -> bahan_makanan.BahanMakananResponse
	6, // 11: bahan_makanan.BahanMakananService.GetBahanMakananById:output_type -> bahan_makanan.BahanMakananResponse
	7, // 12: bahan_makanan.BahanMakananService.GetBahanMakananByMentahOlahan:output_type -> bahan_makanan.ListBahanMakananResponse
	7, // 13: bahan_makanan.BahanMakananService.GetBahanMakananByKelompok:output_type -> bahan_makanan.ListBahanMakananResponse
	6, // 14: bahan_makanan.BahanMakananService.UpdateBahanMakanan:output_type -> bahan_makanan.BahanMakananResponse
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_init() }
func file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_init() {
	if File_src_grpc_proto_bahan_makanan_bahan_makanan_proto != nil {
		return
	}
	file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDesc), len(file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_goTypes,
		DependencyIndexes: file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_depIdxs,
		MessageInfos:      file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_msgTypes,
	}.Build()
	File_src_grpc_proto_bahan_makanan_bahan_makanan_proto = out.File
	file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_goTypes = nil
	file_src_grpc_proto_bahan_makanan_bahan_makanan_proto_depIdxs = nil
}
